version: '3'
services:
  vue-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork

  laravel-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
