version: '3'
services:
  angular-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork

  python-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
