version: '3'
services:
  react-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork

  node-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
